### ISSUE TITLE
Inability to swipe the slider after using setProgress()

### ISSUE THREAD

**Issue by v15a1** [jane/JaneSliderControl#18] opened 2020-08-22 19:14 UTC
Hey,

following up to #17.  I used the setProgress() method to set the state of the slider, which worked fine In setting the state. But after setting the progress to 1, I could not slide it back and forth. i.e It was stuck at 1. 
<img width="166" alt="Screenshot 2020-08-23 at 00 37 41" src="https://user-images.githubusercontent.com/46480892/90963906-8514f200-e4d9-11ea-8178-8fb9418053dc.png">
This is what the slider looks like

What I have done here

1. added a UILabel (unobtrusive to the sliding of the slider) - Tested 
2. set the progress to 1

**Comment by gordontucker** [comment] 2020-08-24 16:46
That _is_ a problem. I'll fix really quick.

**Comment by gordontucker** [comment] 2020-08-24 16:55
So it does let you slide again, but it only currently lets you grab the end (as if there were a dial there like on the UISwitch). While not a bug, per say, I agree there should be an option to allow you to drag anywhere. I'll look into adding that.

**Comment by gordontucker** [comment] 2020-08-24 17:33
This is fixed in 2.1.2

**Closed by gordontucker** 2020-08-24 17:33 UTC
